<a href="https://colab.research.google.com/github/kulraj97/campusx/blob/main/session_15_numpy_tricks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [2]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([37, 26, 90, 26, 67, 55, 51, 43, 92,  6, 48, 70, 59, 39, 46])

In [ ]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[12, 52, 42,  6],
       [29, 18, 47, 55],
       [61, 93, 83,  9],
       [38, 63, 44, 85],
       [ 8, 87, 31, 72],
       [40, 71,  2,  7]])

In [5]:
np.sort(a)[::-1]

array([92, 90, 70, 67, 59, 55, 51, 48, 46, 43, 39, 37, 26, 26,  6])

In [ ]:
np.sort(b,axis=0)

array([[ 8, 18,  2,  6],
       [12, 52, 31,  7],
       [29, 63, 42,  9],
       [38, 71, 44, 55],
       [40, 87, 47, 72],
       [61, 93, 83, 85]])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [ ]:
# code
np.append(a,200)

array([ 11,  53,  28,  50,  38,  37,  94,  92,   5,  30,  68,   9,  78,
         2,  21, 200])

In [ ]:
b

array([[12, 52, 42,  6],
       [29, 18, 47, 55],
       [61, 93, 83,  9],
       [38, 63, 44, 85],
       [ 8, 87, 31, 72],
       [40, 71,  2,  7]])

In [ ]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[12.        , 52.        , 42.        ,  6.        ,  0.22006275],
       [29.        , 18.        , 47.        , 55.        ,  0.81740634],
       [61.        , 93.        , 83.        ,  9.        ,  0.89146072],
       [38.        , 63.        , 44.        , 85.        ,  0.84519124],
       [ 8.        , 87.        , 31.        , 72.        ,  0.24007274],
       [40.        , 71.        ,  2.        ,  7.        ,  0.48056374]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [ ]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [ ]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [ ]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [ ]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [ ]:
# code
a.shape

(15,)

In [ ]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [ ]:
np.expand_dims(a,axis=1)

array([[11],
       [53],
       [28],
       [50],
       [38],
       [37],
       [94],
       [92],
       [ 5],
       [30],
       [68],
       [ 9],
       [78],
       [ 2],
       [21]])

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [ ]:
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

In [ ]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 1,  6,  7, 10, 12]),)

In [ ]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([11,  0, 28, 50, 38, 37,  0,  0,  5, 30,  0,  9,  0,  2, 21])

In [ ]:
np.where(a%2 == 0,0,a)

array([11, 53,  0,  0,  0, 37,  0,  0,  5,  0,  0,  9,  0,  0, 21])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [ ]:
# code
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

In [ ]:
np.argmax(a)

6

In [ ]:
b

array([[12, 52, 42,  6],
       [29, 18, 47, 55],
       [61, 93, 83,  9],
       [38, 63, 44, 85],
       [ 8, 87, 31, 72],
       [40, 71,  2,  7]])

In [ ]:
np.argmax(b,axis=0)

array([2, 2, 2, 3])

In [ ]:
# np.argmin

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [ ]:
# np.cumprod

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis. 

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [ ]:
a

array([24,  1, 34, 54, 36, 24, 28, 89, 91, 31, 64,  5, 54, 93,  3])

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [ ]:
# code
a

array([24,  1, 34, 54, 36, 24, 28, 89, 91, 31, 64,  5, 54, 93,  3])

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [ ]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [ ]:
# code
a

array([24,  1, 34, 54, 36, 24, 28, 89, 91, 31, 64,  5, 54, 93,  3])

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [ ]:
# code

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array. 

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [ ]:
# code

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis. 

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [ ]:
# code

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [ ]:
# code

In [ ]:
# 17. np.swapaxes

In [ ]:
# 18. np.uniform

In [ ]:
# 19. np.count_nonzero

In [ ]:
# 21. np.tile
# https://www.kaggle.com/code/abhayparashar31/best-numpy-functions-for-data-science-50?scriptVersionId=98816580

In [ ]:
# 22. np.repeat
# https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5

In [ ]:

# 25. np.allclose and equals